// Generated by scripts/generate-build-info.js at build time — do not edit by hand.
export const BuildInfo: { commit: string; commitShort: string; builtAt: string } = {
  commit: '4b4ded95801236c9c35deb645cc4a8b64740822c',
  commitShort: '4b4ded9',
  builtAt: '2026-09-05T23:52:28.794Z',
};
